# Generated by Django 5.0.3 on 2024-05-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0005_alter_customuser_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("librarian", "Librarian"), ("user", "User")],
                default="user",
                max_length=50,
            ),
        ),
    ]
