# Generated by Django 5.0.3 on 2024-06-05 22:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Unknown Author",
                        max_length=100,
                        unique=True,
                        verbose_name="Author Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Unknown Genre",
                        max_length=100,
                        unique=True,
                        verbose_name="Genre Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "publish_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date of Publish",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantity of Stock"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.author",
                        verbose_name="Author",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.genre",
                        verbose_name="Genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.CreateModel(
            name="BookReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reserved_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creates automatically",
                        verbose_name="Reserved Date",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/time when reservation expires",
                        null=True,
                        verbose_name="Expiration Date",
                    ),
                ),
                (
                    "reservation_status",
                    models.CharField(
                        choices=[("reserved", "Reserved"), ("picked_up", "Picked Up")],
                        default="reserved",
                        max_length=50,
                        verbose_name="Reservation Status",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="library_app.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Borrower",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Reservation",
                "verbose_name_plural": "Book Reservations",
                "ordering": ["-reserved_date"],
            },
        ),
        migrations.CreateModel(
            name="BooksBorrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrowed_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creates automatically",
                        verbose_name="Borrowed Date",
                    ),
                ),
                (
                    "borrowed_status",
                    models.CharField(
                        choices=[("borrowed", "Borrowed"), ("returned", "Returned")],
                        default="borrowed",
                        max_length=50,
                        verbose_name="Borrowed Status",
                    ),
                ),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/time of returning borrowed book",
                        null=True,
                        verbose_name="Return Date",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrows",
                        to="library_app.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Borrower",
                    ),
                ),
            ],
            options={
                "verbose_name": "Books Borrow",
                "verbose_name_plural": "Books Borrows",
                "ordering": ["-borrowed_date"],
            },
        ),
    ]
