# Generated by Django 5.0.3 on 2024-05-25 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0003_alter_book_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Unknown Genre",
                        max_length=100,
                        unique=True,
                        verbose_name="Genre Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Author", "verbose_name_plural": "Authors"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Book", "verbose_name_plural": "Books"},
        ),
        migrations.RemoveField(
            model_name="author",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="author",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="book",
            name="date_of_publish",
        ),
        migrations.RemoveField(
            model_name="book",
            name="quantity_in_stock",
        ),
        migrations.AddField(
            model_name="author",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="author",
            name="name",
            field=models.CharField(
                default="Unknown Author",
                max_length=100,
                unique=True,
                verbose_name="Author Name",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publish_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date of Publish"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantity of Stock"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="library_app.author",
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="library_app.genre",
                verbose_name="Genre",
            ),
        ),
        migrations.DeleteModel(
            name="PreOrder",
        ),
    ]
